name: DuinoCoin Miner

on:
  schedule:
    # 北京时间 08:00  -> UTC 00:00
    - cron: "0 0 * * *"
    # 北京时间 13:35  -> UTC 05:35
    - cron: "35 5 * * *"
    # 北京时间 19:10  -> UTC 11:10
    - cron: "10 11 * * *"
    # 北京时间 00:45  -> UTC 16:45 (前一天)
    - cron: "45 16 * * *"
    # 北京时间 06:20  -> UTC 22:20 (前一天)
    - cron: "20 22 * * *"
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run miner for 5.5 hours
        run: |
          echo "开始挖矿 (最多 5.5 小时)"
          timeout 19800 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"
