name: DuinoCoin WAKUANG

on:
  schedule:
    # 北京时间 08:00  -> UTC 00:00
    - cron: "0 0 * * *"
    # 北京时间 14:00  -> UTC 06:00
    - cron: "0 6 * * *"
    # 北京时间 20:00  -> UTC 12:00
    - cron: "0 12 * * *"
    # 北京时间 02:00  -> UTC 18:00
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  # 第一个
  worker-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 5 hours 58 minutes
        run: |
          echo "开始挖矿 #1 (最多 5小时58分钟)"
          timeout 21480 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"

  # 第二个任务，与第一个并行运行
  worker-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 5 hours 58 minutes
        run: |
          echo "开始挖矿 #2 (最多 5小时58分钟)"
          timeout 21480 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"

  # 第三个任务，与前两个并行运行
  worker-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 5 hours 58 minutes
        run: |
          echo "开始挖矿 #3 (最多 5小时58分钟)"
          timeout 21480 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"

  # 第四个任务，与前三个并行运行
  worker-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 5 hours 58 minutes
        run: |
          echo "开始挖矿 #4 (最多 5小时58分钟)"
          timeout 21480 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"

  # 第五个任务，与前四个并行运行
  worker-5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 5 hours 58 minutes
        run: |
          echo "开始挖矿 #5 (最多 5小时58分钟)"
          timeout 21480 python3 PC_Miner.py || true
          echo "本轮结束，等待下一个调度自动运行"
