name: DuinoCoin WAKUANG 2h MAX

on:
  schedule:
    # 每 2.5 小时触发一次（UTC）
    # 例：00:00, 02:30, 05:00, 07:30, 10:00 ...
    - cron: "0 */5 * * *"   # 这是每5小时，不是2.5小时
    - cron: "30 */5 * * *"  # 加上半小时的点
  workflow_dispatch:

jobs:
  worker-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama

      - name: Run for 2 hours
        run: |
          echo "开始挖矿 #1 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #2 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #3 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #4 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #5 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #6 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"

  worker-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install requests colorama
      - run: |
          echo "开始挖矿 #7 (最多 2 小时)"
          timeout 7200 python3 PC_Miner.py || true
          echo "结束，本轮已运行 2 小时"
